[2020-04-13T15:23:00.926] [ERROR] errorLog - 
***** error log start *****
request originalUrl: /api/artical/getDetail?id=5e4e4aa2b8620637839d8d3c&t=1586762580851
request client ip: 127.0.0.1
request query: {"id":"5e4e4aa2b8620637839d8d3c","t":"1586762580851"}
response time: undefined
error name: SyntaxError
error message: Unexpected token u in JSON at position 0
error stack: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at exports.getArticalDetail (D:\blog-server\src\controller\artical.js:45:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
***** error log end ******

[2020-04-13T15:24:01.481] [ERROR] errorLog - 
***** error log start *****
request originalUrl: /api/artical/getDetail?id=5e4e4aa2b8620637839d8d3c&t=1586762641386
request client ip: 127.0.0.1
request query: {"id":"5e4e4aa2b8620637839d8d3c","t":"1586762641386"}
response time: undefined
error name: SyntaxError
error message: Unexpected token u in JSON at position 0
error stack: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at exports.getArticalDetail (D:\blog-server\src\controller\artical.js:45:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
***** error log end ******

[2020-04-13T15:24:39.063] [ERROR] errorLog - 
***** error log start *****
request originalUrl: /api/artical/getDetail?id=5e4e4aa2b8620637839d8d3c&t=1586762678971
request client ip: 127.0.0.1
request query: {"id":"5e4e4aa2b8620637839d8d3c","t":"1586762678971"}
response time: undefined
error name: SyntaxError
error message: Unexpected token u in JSON at position 0
error stack: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at exports.getArticalDetail (D:\blog-server\src\controller\artical.js:45:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
***** error log end ******

[2020-04-13T15:39:01.877] [ERROR] errorLog - 
***** error log start *****
request originalUrl: /api/artical/getDetail?id=5e4e4aa2b8620637839d8d3c&t=1586763541797
request client ip: 127.0.0.1
request query: {"id":"5e4e4aa2b8620637839d8d3c","t":"1586763541797"}
response time: undefined
error name: ServiceUnavailableError
error message: 查询数据库出错！
error stack: ServiceUnavailableError: 查询数据库出错！
    at Object.throw (D:\blog-server\node_modules\_koa@2.11.0@koa\lib\context.js:97:11)
    at Object.ctx.error (D:\blog-server\src\app.js:53:14)
    at exports.getArticalDetail (D:\blog-server\src\controller\artical.js:43:9)
    at router.get (D:\blog-server\src\router\artical.js:22:20)
    at dispatch (D:\blog-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (D:\blog-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at D:\blog-server\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:346:16
    at dispatch (D:\blog-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at D:\blog-server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
    at dispatch (D:\blog-server\node_modules\_koa-router@7.4.0@koa-router\lib\router.js:351:31)
    at dispatch (D:\blog-server\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at app.use (D:\blog-server\src\app.js:96:9)
    at dispatch (D:\blog-server\node_modules\_koa-compose@4.1.0@koa-compose\index.js:42:32)
    at D:\blog-server\node_modules\_koa-generic-session@2.0.4@koa-generic-session\lib\session.js:280:15
    at Generator.next (<anonymous>)
    at step (D:\blog-server\node_modules\_koa-generic-session@2.0.4@koa-generic-session\lib\session.js:3:191)
***** error log end ******

